#!/bin/bash
echo "This updates the existing githubs"
echo "Fill the array with the original folders first"

# use ls -d */ > list to get the list of the created githubs and copy/paste in

directories=(aic94xx-firmware/
alacritty-themes/
albert/
alpm_octopi_utils/
alsi/
amberol/
android-sdk-platform-tools/
anydesk-bin/
appimagelauncher/
apm/
arc-darkest-theme-git/
arc-kde/
arc-x-icons-theme/
ast-firmware/
aura-bin/
auto-cpufreq/
autologin/
autotiling/
autotiling-git/
azote/
base16-alacritty-git/
bash-pipes/
bauh/
betterlockscreen-git/
bibata-cursor-theme-bin/
bibata-rainbow-cursor-theme/
bibata-cursor-translucent/
bibata-extra-cursor-theme/
blender-benchmark/
boxes/
brillo/
btrfs-assistant/
btrfs-assistant-git/
btrfs-du/
btrfsmaintenance/
btrfsmaintenance-git/
bumblebee-status/
bumblebee-status-git/
byte/
caffeine-ng/
catch2-git/
cava/
chrome-gnome-shell/
chromium-widevine/
ckbcomp/
ckb-next-git/
clapper/
clementine/
clipman/
c-lolcat/
cpu-x/
cwm/
cxxmatrix-git/
cmatrix-git/
cnijfilter2-mg7700/
conky-lua-archers/
conky-lua-archers-git/
cpuid/
cpufetch-git/
curseradio-git/
dbus-go/
deadbeef/
debtap/
deezer/
discord_arch_electron/
disper/
dk/
downgrade/
dracula-cursors-git/
dracula-gtk-theme/
dracula-icons-git/
droidcam/
edid-decode-git/
enlightenment-arc-theme-git/
enpass-bin/
envycontrol/
esbuild/
eww/
extremetuxracer/
fancontrol-gui-git/
fastfetch/
fastfetch-git/
filebot/
find-the-command-git/
fingerprint-gui/
flameshot-git/
flavours/
fluent-gtk-theme/
fluent-kde-theme-git/
fmt9/
fnott-git/
font-manager-git/
fonts-tlwg/
freedownloadmanager/
fundle-git/
fvwm3-git/
g4music/
game-devices-udev/
gamehub-bin/
gammy/
gconf/
gdown/
gitahead-bin/
gksu/
glxinfo/
gmusicbrowser/
gnome-doc-utils/
gnome-icon-theme/
gnome-icon-theme-symbolic/
gnome-shell-extension-appindicator-git/
gnome-shell-extension-pop-shell-git/
gnome-shell-extension-dash-to-dock/
gnome-system-tools/
gnome-terminal-transparency/
golang-github-godbus-dbus/
gopsuinfo/
gotop-bin/
goverlay-bin/
gputest/
greetd/
greetd-wlgreet/
grimshot/
graphite-gtk-theme-git/
gtk-sharp-2-git/
gtklock/
gtklock-userinfo-module/
gtklock-powerbar-module/
gtklock-playerctl-module/
gummy/
gwe/
halo-icons-git/
hardcode-fixer-git/
hardinfo-gtk3/
halo-icons-git/
hypnotix/
hyprland-git/
hyprland-nvidia/
hyprland-nvidia-git/
hyprpicker-git/
hyprpaper-git/
hyprshot/
hw-probe/
i3lock-color/
itch/
jade-application-kit/
jdownloader2/
jwm/
imagewriter/
iso-flag-png/
jamesdsp/
jamesdsp-pulse/
kazam/
kickoff/
konsave/
kripton-theme-git/
ksuperkey/
kvantum-theme-qogir-git/
kvantum-qt5-git/
kvantum-qt6-git/
kwin-bismuth/
kwin-bismuth-bin/
kwin-scripts-krohnkite-git/
kwin-scripts-forceblur/
la-capitaine-icon-theme-git/
lavalauncher/
lastpass/
layan-cursor-theme-git/
layan-gtk-theme-git/
layan-kde-git/
leftwm/
leftwm-git/
leftwm-config-git/
leftwm-config/
leftwm-theme-git/
legendary/
libart-lgpl/
libblocksruntime/
libdispatch/
libfprint-1/
libgbinder/
libglade/
libglibutil/
libgksu/
liboobs/
lightdm-settings/
lightdm-webkit-theme-aether/
lightdm-webkit2-theme-reactive/
linux-wifi-hotspot/
lohit-fonts/
lxdm-themes/
lxqt-arc-dark-theme-git/
ly/
makemkv/
mate-tweak/
mawk/
mcomix/
megasync-bin/
menulibre/
min/
minigalaxy/
mintlocale/
mintstick-git/
mkinitcpio-firmware/
modprobed-db/
modprobed-db-git/
mono-upnp-git/
mono-zeroconf-git/
mozilla-common/
ms-office-online/
mugshot/
multimc-git/
nautilus-open-any-terminal/
nerd-fonts-source-code-pro/
newm-git/
nixieclock/
nodejs-nativefier/
nomacs/
nomacs-git/
nordic-kde-git/
nordtray-bin/
nordvpn-bin/
nvflash/
numix-circle-icon-theme-git/
numix-gtk-theme-git/
numix-icon-theme-git/
numix-kde-theme-git/
nvidia-xrun/
nvtop-git/
nwg-bar-bin/
nwg-displays/
nwg-dock-bin/
nwg-drawer-bin/
nwg-icon-picker/
nwg-dock-hyprland-bin/
nwg-launchers/
nwg-look-bin/
nwg-menu-bin/
nwg-panel/
nwg-shell/
nwg-shell-wallpapers/
nwg-shell-config/
nwg-wrapper/
nyrna/
obmenu3/
obmenu-generator/
obsidian-icon-theme/
ocs-url/
octopi/
oh-my-zsh-git/
oh-my-zsh-powerline-theme-git/
olivia/
ookla-speedtest-bin/
openbox-arc-git/
openbox-themes-pambudi-git/
openrgb/
optimus-manager/
optimus-manager-qt/
orchis-kde-theme-git/
orchis-theme-git/
oranchelo-icon-theme-git/
oxy-neon/
playonlinux/
pm2ml/
pa-applet-git/
pacback/
pace/
pace-git/
pacseek-bin/
pamac-tray-icon-plasma/
papirus-linux-universe/
papirus-nord/
papirus-folders/
papirus-folders-git/
papirus-folders-gui/
papirus-folders-gui-bin/
papirus-folders-nordic/
paru/
paru-bin/
paru-git/
perl-checkupdates-aur/
perl-linux-desktopfiles/
perl-www-aur/
pev/
pev-git/
picom-git/
picom-ibhagwan-git/
picom-jonaburg-git/
pikaur-git/
pfetch/
phinger-cursors/
phoronix-test-suite/
plata-theme/
plymouth/
plymouth-git/
plymouth-theme-monoarch/
pnmixer/
ponymix/
pop-launcher-git/
pop-shell-shortcuts-git/
powerpill/
prot16-xfce4-terminal/
proton-community-updater
protonvpn/
protonvpn-cli/
protonvpn-gui/
protonup-git/
protontricks/
protontricks-git/
pycrc/
pygtk/
python2-cairo/
python2-gobject/
python2-gobject2/
python2-libxml2/
python3-memoizedb/
python3-xcgf/
python3-xcpf/
python-cinemagoer/
python-dasbus/
python-clickgen/
python-clickgen1/
python-gbinder/
python-grpcio-tools/
python-hsaudiotag3k/
python-imageio/
python-injector/
python-inotify-simple/
python-isounidecode/
python-pid/
python-polib/
python-proton-client/
python-protonvpn-nm-lib/
python-pulse-control/
python-pulsectl/
python-py3nvml/
python-pylyrics/
python-pypresence
python-pysdl2/
python-stagger/
python-suntime/
python-tekore/
python-thefuzz/
python-transitions/
python-vdf/
qobbar-git/
qogir-icon-theme/
qogir-kde-theme-git/
qogir-gtk-theme-git/
qt4/
qtscrcpy/
quickemu/
quickemu-git/
quickgui-bin/
quicktile/
qtwebflix-git/
qt5-webkit/
radiotray/
rare/
rarian/
rate-mirrors/
rate-mirrors-bin/
realvnc-vnc-server/
realvnc-vnc-viewer/
refind-btrfs/
replay-sorcery/
retroarch-autoconfig-udev-git/
river/
rofi-lbonn-wayland-only-git/
rplay/
rtl8821cu-morrownr-dkms-git/
r8168-dkms/
sakura/
sayonara-player/
scangearmp2-mg7700/
screenkey-git/
sdbus-cpp/
sddm-git/
sddm-sugar-candy-git/
shell-color-scripts/
shim-signed/
shortwave/
shotman/
simplicity-sddm-theme-git/
simplescreenrecorder-git/
slimbookbattery/
slstatus-git/
slurm/
sparklines-git/
spectrwm/
spectrwm-git/
speedtest-cli-git/
spotify-adblock-git/
spotifywm-git/
snap-pac-git/
snap-pac-grub/
snapper-rollback/
snapper-support/
snapper-tools/
snapper-tools-git/
spdlog-git/
steamtinkerlaunch/
sway-git/
swaybg-git/
swaync/
swayr/
swaysome-git/
sweet-gtk-theme-dark/
sweet-theme-git/
stacer/
stacer-bin/
steam-buddy/
steam-tweaks/
sublime-text-4/
sutils-git/
system76-power/
systemd-boot-pacman-hook/
systemd-kcm/
systemd-manager-git/
system-tools-backends/
sxhkd-git/
taglib-extras/
taglib-sharp-git/
tauon-music-box/
tempus-themes-xfce4-terminal-git/
termite/
the_platinum_searcher-bin/
timeshift-autosnap/
#thunar-extended/
thunar-shares-plugin/
thunar-shares-plugin-git/
toilet/
topgrade-bin/
topgrade-git/
trizen/
ttf-mac-fonts/
tuxboot/
tuxboot-git/
ttf-hellvetica/
ttf-material-design-iconic-font/
ttf-meslo-nerd-font-powerlevel10k/
ttf-ms-fonts/
ttf-hactor/
tty-clock/
tty-clock-git/
tweetdeck-desktop/
upd72020x-fw/
ufetch-git/
unimatrix-git/
ulauncher/
urxvt-fullscreen/
urxvt-resize-font-git/
ventoy-bin/
vimix-cursors/
vimix-icon-theme-git/
vkbasalt/
vlc-luajit/
volctl/
we10x-icon-theme-git/
wacom-settings-git/
wacom-utility/
waydroid/
whitesur-icon-theme-git/
wlprop/
wlr-randr/
wlr-randr-git/
wlroots-git/
wob/
wob-git/
vmware-keymaps/
vtop/
waybar-hyprland-git
wayfire/
wcm/
wd719x-firmware/
wdisplays/
wdisplays-git/
webapp-manager/
wf-config/
wf-recorder-git/
wf-shell/
wlogout/
wlsunset/
wmderland-git/
woeusb/
wttr/
wyvern/
xcursor-arch-cursor-complete/
xcursor-breeze/
xcursor-flatbed/
xcursor-neutral/
xcursor-premium/
xcursor-simpleandsoft/
xdgmenumaker/
xdman/
xfce4-screensaver-git/
xlunch-git/
xmonad-log/
xsnow-bin/
xtitle-git/
yay/
yay-bin/
yay-git/
yin-yang-git/
xkb-switch-git/
xkblayout-state-git/
xfce4-panel-profiles/
xfce4-terminal-base16-colors-git/
xstarter/
xmobar-dynamic/
yofi-bin/
youtube-dl-gui-git/
zafiro-icon-theme/
zsh-autosuggestions-git/
zsh-fast-syntax-highlighting/
zsh-history-substring-search-git/
zsh-syntax-highlighting-git/
zsh-theme-powerlevel10k-git
)

count=0

for name in "${directories[@]}"; do
	count=$[count+1]
	tput setaf 1;echo "Github "$count;tput sgr0;
	git clone https://aur.archlinux.org/$name
	echo "#################################################"
	echo "################  "$(basename `pwd`)" done"
	echo "#################################################"
done

git clone https://github.com/chaotic-aur/pkgbuild-chaotic-keyring

git clone https://github.com/chaotic-aur/pkgbuild-chaotic-mirrorlist

git clone https://github.com/xerolinux/xerolinux-mirrorlist

git clone https://github.com/RebornOS-Developers/rebornos-mirrorlist.git

git clone https://github.com/RebornOS-Developers/rebornos-keyring.git

echo
echo "###################################################################"
echo "Check Rebornos, Endeavouros keyring and mirror from time to time"