#!/bin/bash
echo "This updates the existing githubs"
echo "Fill the array with the original folders first"

# use ls -d */ > list to get the list of the created githubs and copy/paste in

directories=(
alpm_octopi_utils/
arc-kde/
autotiling/
bash-pipes/
bibata-cursor-theme/
boxes/
caffeine/
caffeine-ng/
cava/
chaotic-keyring/
chaotic-mirrorlist/
cwm/
cxxmatrix-git/
cmatrix-git/
cnijfilter2-mg7700/
conky-lua-archers/
cpufetch-git/
curseradio-git/
dbus-go/
discord_arch_electron/
disper/
downgrade/
edid-decode-git/
enlightenment-arc-theme-git/
font-manager-git/
fvwm3-git/
gconf/
gitahead-bin/
gksu/
glxinfo/
gnome-shell-extension-appindicator-git/
gnome-shell-extension-pop-shell-git/
gnome-shell-extension-dash-to-dock/
gotop-bin/
halo-icons-git/
hardcode-fixer-git/
halo-icons-git/
hypnotix/
hw-probe/
i3lock-color/
imagewriter/
inxi/
iso-flag-png/
kazam/
ksuperkey/
lastpass/
legendary/
libgksu/
lxqt-arc-dark-theme-git/
mate-tweak/
megasync-nopdfium/
menulibre/
mintlocale/
mintstick-git/
mugshot/
nodejs-nativefier/
numix-circle-arc-icons-git/
numix-circle-icon-theme-git/
numix-gtk-theme-git/
numix-icon-theme-git/
numix-kde-theme-git/
nvidia-xrun/
obkey-git/
obmenu3/
obmenu-generator/
ocs-url/
octopi/
oh-my-zsh-git/
openbox-arc-git/
openbox-themes-pambudi-git/
optimus-manager/
optimus-manager-qt/
oxy-neon/
pm2ml/
pacback/
pamac-aur/
pamac-all/
paru-bin/
perl-checkupdates-aur/
perl-linux-desktopfiles/
perl-www-aur/
pfetch/
polybar/
pop-shell-shortcuts-git/
powerpill/
pycrc/
pygtk/
python3-memoizedb/
python3-xcgf/
python3-xcpf/
python-clickgen/
python-grpcio-tools/
python-hsaudiotag3k/
python-inotify-simple/
python-isounidecode/
python-pulse-control/
python-pulsectl/
python-pynacl/
python-pysdl2/
python-pyparted/
python-pylyrics/
python-stagger/
python-suntime/
python-tekore/
python-vdf/
qobbar-git/
quicktile/
radiotray/
retroarch-autoconfig-udev-git/
rplay/
scangearmp2-mg7700/
screenkey-git/
sddm-sugar-candy-git/
slimbookbattery/
slstatus-git/
slurm/
spotifywm-git/
snapd/
snapd-glib/
stacer/
steam-buddy/
steam-tweaks/
sublime-text-dev/
sutils-git/
systemd-kcm/
systemd-manager/
tauon-music-box/
the_platinum_searcher-bin/
timeshift/
timeshift-autosnap/
theme.sh-git/
thunar-shares-plugin/
toilet/
trizen/
ttf-hellvetica/
ttf-ms-fonts/
tty-clock/
ufetch-git/
urxvt-resize-font-git/
ventoy-bin/
warpinator/
woeusb/
wttr/
wyvern/
xcursor-breeze/
xdgmenumaker/
xfce4-panel-profiles/
xmonad-log/
xtitle-git/
yay-bin/
yin-yang-git/
zafiro-icon-theme/
zscroll-git/
zsh-completions-git/
zsh-syntax-highlighting-git/
)

count=0

for name in "${directories[@]}"; do
	count=$[count+1]
	tput setaf 1;echo "Github "$count;tput sgr0;
	git clone https://aur.archlinux.org/$name
	echo "#################################################"
	echo "################  "$(basename `pwd`)" done"
	echo "#################################################"
done
